---
application:
  name: "shopper-api-git-hub"
  project: "shopper"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "shopper"
  version: "4.4"
routers:
- name: "main-shopper-api-git-hub"
  routes:
  - application_name: "shopper-api-git-hub"
    paths:
    - "/*"
